name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          gh-actions-learn/second-action-react-project
          echo "${{ toJSON(github) }}"
